/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve */
        post: operations["resolve_api_resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Batch */
        post: operations["probe_batch_api_batch_probe_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Batch */
        post: operations["verify_batch_api_batch_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batch/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue Batch */
        post: operations["queue_batch_api_batch_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/batches/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Batch */
        get: operations["get_batch_api_batches__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description Live events only. Clients reconcile against GET /jobs on connect.
         */
        get: operations["job_events_api_jobs_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Cancel Job */
        delete: operations["cancel_job_api_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Library */
        get: operations["list_library_api_library_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/library/{item_id}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Library File */
        get: operations["get_library_file_api_library__item_id__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_settings_get"];
        /** Put Settings */
        put: operations["put_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchItemOut */
        BatchItemOut: {
            /** Url */
            url: string;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** BatchOut */
        BatchOut: {
            /** Id */
            id: string;
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Capability
             * @default
             */
            capability: string;
            /**
             * Confidence
             * @default
             */
            confidence: string;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /** Jobs */
            jobs: components["schemas"]["JobOut"][];
            /** Skipped */
            skipped: string[];
        };
        /** BatchProbeIn */
        BatchProbeIn: {
            /** Url */
            url: string;
        };
        /** BatchProbeOut */
        BatchProbeOut: {
            /** Capability */
            capability: string;
            /** Confidence */
            confidence: string;
            /** Batchable */
            batchable: boolean;
            /** Items */
            items: components["schemas"]["BatchItemOut"][];
            /** Total Estimate */
            total_estimate?: number | null;
            /**
             * Truncated
             * @default false
             */
            truncated: boolean;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /** BatchQueueIn */
        BatchQueueIn: {
            /** Items */
            items: components["schemas"]["BatchItemOut"][];
            /**
             * Source Url
             * @default
             */
            source_url: string;
            /**
             * Capability
             * @default
             */
            capability: string;
            /**
             * Confidence
             * @default
             */
            confidence: string;
        };
        /** BatchVerifyIn */
        BatchVerifyIn: {
            /** Items */
            items: components["schemas"]["BatchItemOut"][];
            /**
             * Count
             * @default 2
             */
            count: number;
        };
        /** BatchVerifyOut */
        BatchVerifyOut: {
            /** Verified */
            verified: number;
            /** Attempted */
            attempted: number;
        };
        /** FormatOut */
        FormatOut: {
            /** Format Id */
            format_id: string;
            /** Label */
            label: string;
            /** Track */
            track: string;
            /** Container */
            container?: string | null;
            /** Height */
            height?: number | null;
            /** Fps */
            fps?: number | null;
            /** Vcodec */
            vcodec?: string | null;
            /** Acodec */
            acodec?: string | null;
            /** Filesize */
            filesize?: number | null;
            /** Tbr */
            tbr?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Ok
             * @description False when a required external tool is missing
             */
            ok: boolean;
            /** Tools */
            tools: components["schemas"]["ToolStatusOut"][];
            /** Ytdlp Version */
            ytdlp_version?: string | null;
            /** Free Bytes */
            free_bytes?: number | null;
            /** Output Dir */
            output_dir: string;
            /** Plugins */
            plugins: string[];
        };
        /** JobCreateIn */
        JobCreateIn: {
            /** Url */
            url?: string | null;
            /** Resolution Id */
            resolution_id?: string | null;
            /** Format Id */
            format_id?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
        };
        /** JobOut */
        JobOut: {
            /** Id */
            id: string;
            /** Url */
            url: string;
            /** Batch Id */
            batch_id?: string | null;
            /**
             * Engine
             * @default
             */
            engine: string;
            /** Format Id */
            format_id?: string | null;
            /**
             * Title
             * @default
             */
            title: string;
            /** Output Path */
            output_path?: string | null;
            /** Status */
            status: string;
            /** Phase */
            phase: string;
            /** Percent */
            percent?: number | null;
            /** Downloaded Bytes */
            downloaded_bytes?: number | null;
            /** Total Bytes */
            total_bytes?: number | null;
            /** Speed Bps */
            speed_bps?: number | null;
            /** Eta Seconds */
            eta_seconds?: number | null;
            /** Error */
            error?: string | null;
            /**
             * Created At
             * @default
             */
            created_at: string;
            /**
             * Updated At
             * @default
             */
            updated_at: string;
        };
        /** LibraryItemOut */
        LibraryItemOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Size Bytes */
            size_bytes: number;
            /** Modified At */
            modified_at: number;
        };
        /** ResolveIn */
        ResolveIn: {
            /** Url */
            url: string;
            /** Engines */
            engines?: string[] | null;
        };
        /** ResolveOut */
        ResolveOut: {
            /** Resolution Id */
            resolution_id: string;
            /** Engine */
            engine: string;
            /** Url */
            url: string;
            /** Final Url */
            final_url: string;
            /** Title */
            title: string;
            /** Duration */
            duration?: number | null;
            /** Thumbnail */
            thumbnail?: string | null;
            /** Uploader */
            uploader?: string | null;
            /** Formats */
            formats: components["schemas"]["FormatOut"][];
            /**
             * Item Count
             * @default 1
             */
            item_count: number;
        };
        /** SettingsIn */
        SettingsIn: {
            /** Output Dir */
            output_dir?: string | null;
            /** Concurrency */
            concurrency?: number | null;
            /** Engines */
            engines?: string[] | null;
            /** Default Format */
            default_format?: string | null;
            /** Ffmpeg Location */
            ffmpeg_location?: string | null;
            /** Cookies From Browser */
            cookies_from_browser?: string | null;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Output Dir */
            output_dir: string;
            /** Concurrency */
            concurrency: number;
            /** Engines */
            engines: string[];
            /** Default Format */
            default_format: string;
            /** Ffmpeg Location */
            ffmpeg_location: string;
            /** Cookies From Browser */
            cookies_from_browser: string;
            /** Host */
            host: string;
            /** Port */
            port: number;
        };
        /** ToolStatusOut */
        ToolStatusOut: {
            /** Name */
            name: string;
            /** Required */
            required: boolean;
            /** Available */
            available: boolean;
            /** Path */
            path?: string | null;
            /** Version */
            version?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    resolve_api_resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolveOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_batch_api_batch_probe_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchProbeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchProbeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_batch_api_batch_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchVerifyIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchVerifyOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_batch_api_batch_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchQueueIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_batch_api_batches__batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                status?: string;
                batch_id?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_library_api_library_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryItemOut"][];
                };
            };
        };
    };
    get_library_file_api_library__item_id__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    put_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
